### ISSUE TITLE
HTTPS Everywhere Atlas is lagging behind master

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere-atlas#8]
For example

https://www.eff.org/https-everywhere/atlas/domains/prnt.sc.html vs https://github.com/EFForg/https-everywhere/blob/9c5f5ca8bc00e960c9e119c4fe3b6ec0cdc35cd2/src/chrome/content/rules/prnt.sc.xml

Note that at the bottom of the page, it also says

> current release 6a955e7 2018-11-01 05:00:06 -0700;
> next release e7f9f87 2018-12-14 12:11:54 -0700; 

cc @Hainish

**Comment by Hainish** [comment]
Looks like this is outdated, notice that https://atlas.eff.org/domains/prnt.sc.html has the latest release.

I'll open a request to our techops team to forward requests from 

https://www.eff.org/https-everywhere/atlas/$url to https://atlas.eff.org/$url

**Comment by Hainish** [comment]
cc @starchy

**Comment by Hainish** [comment]
This is fixed!
